GitとGitHub用語集のリンクおよび画像を追加した
akht/kagoshima_dot_mk_3 pull request #62
Opened 2019-10-19 17:32 UTC by HouraiSyuto

GitとGitHub用語集を説明する時に必要そうな物を追加した。
- GitとGitHub用語集の説明リンク
- GitとGitHub用語集の画像

2019-10-19 17:32 UTC, HouraiSyuto commented
@akht @hayasaki-shunsuke 
レビューお願いします！

2019-10-19 17:46 UTC, akht requested changes

2019-10-19 17:46 UTC, akht commented on README.md
> +
見出しがリンクになってはいるけど、下の方に画像の引用元を明記しておくといいかなあと思いました！

2019-10-20 10:55 UTC, HouraiSyuto commented on README.md
> +
はい！追記します！

2019-10-20 10:55 UTC, HouraiSyuto commented
@akht 
引用先を記載しまし！再レビューお願いします！

2019-10-20 11:38 UTC, akht commented on README.md
> +
👍

2019-10-20 11:38 UTC, akht approved these changes
Thank you!!!

2019-10-20 11:45 UTC, merged